from pydantic import BaseModel, Field


class Answer(BaseModel):
    """
    LLM response model containing the generated answer.

    This model represents the AI-generated response returned to the user.
    The response is generated by the configured LLM provider and processed
    through the API's retry and error handling mechanisms.
    """

    text: str = Field(
        ...,
        description="AI-generated response text from the LLM provider",
        examples=[
            "Hello! I'm doing well, thank you for asking. How can I assist you today?",
            "Quantum computing is a revolutionary computing paradigm that leverages quantum mechanics...",
            "Here's a Python function to calculate Fibonacci numbers: def fibonacci(n): ...",
        ],
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "text": "Artificial Intelligence (AI) is a branch of computer science focused on creating systems that can perform tasks typically requiring human intelligence."
                },
                {
                    "text": "I'd be happy to help you write a cover letter! Here's a structure you can follow: 1. Header with your contact information..."
                },
                {
                    "text": "REST and GraphQL are both API design approaches, but they differ significantly: REST uses multiple endpoints for different resources..."
                },
            ]
        }
    }
